POST http://localhost:3333/retweets/ HTTP/1.1
content-type: application/json
Authorization: cc57be7c-d9a5-4070-a878-9cbb2fb9b14f

{
    "content": "Cheguei @nat, não precisa mais se sentir sozinha! Heheh 😁",
    "tweetId": "861d4f94-1439-43f8-945a-7d7bd734c9c9"
}