PUT http://localhost:3333/retweets/ HTTP/1.1
content-type: application/json
Authorization:847d2571-e5aa-4a62-832a-8bc9975e612e


{
    "id": "bfb972b2-9b0e-4b74-ad48-59cd258ce2df",
    "content": "MUDEI DE BLA BLA PARA BLU BLU"
}