POST http://localhost:3333/tweets/ HTTP/1.1
content-type: application/json
Authorization: 307749c6-5604-4c3a-883a-0bfff15d0f9e

{
    "content": "Será??",
    "type": "retweet",
    "originalTweetId": "38b36cca-48ee-48bd-9c39-6f6c162ba75e"
}