POST http://localhost:3333/tweets/ HTTP/1.1
content-type: application/json
Authorization: d1a30f73-ea8b-4113-8664-0f4cce81b1f0

{
    "content": "Oi, eu sou o carlos e estou retweetando o tweet do Misa!",
    "type": "retweet",
    "tweetId": "346ec319-4729-4c2a-a83a-636617ccc187"
}