POST http://localhost:3333/likes/ HTTP/1.1
content-type: application/json
Authorization: ffdf1456-5a8e-4873-a0eb-765163853e52

{
    "tweetId": "c0dc8bc6-5084-4cfb-b49e-6ba1131427a5",
    "retweetId":""
}